backend:
  name: github
  repo: pangv/auszweiwirdeins
  branch: main
  base_url: https://sveltia-cms-auth.sven-oliverpaetzel.workers.dev # Hinzugefügt: https://

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "hotels_collection" # Eindeutiger Name für die Collection
    label: "Hotel Empfehlungen"
    files:
      - label: "Alle Hotels"
        name: "hotels_list"
        file: "src/data/hotels.json"
        fields:
          - label: "Hotels"
            name: "hotels"
            widget: "list"
            summary: "{{name}}"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Bild", name: "image", widget: "image" }
              - { label: "Adresse", name: "address", widget: "string" }
              - { label: "Preisspanne", name: "price", widget: "string" }
              - { label: "Entfernung", name: "distance", widget: "text" }
              - { label: "Beschreibung", name: "description", widget: "text" }
              - { label: "Link", name: "link", widget: "text" }
              - { label: "Link-Text", name: "linkText", widget: "text" }

  - name: "faq_collection"
    label: "FAQ"
    files:
      - label: "Alle Fragen"
        name: "faq_list"
        file: "src/data/faq.json"
        fields:
          - label: "FAQ"
            name: "faq"
            widget: "list"
            summary: "{{question}}"
            fields:
              - { label: "Frage", name: "question", widget: "string" }
              - { label: "Antwort", name: "answer", widget: "text" }
              - { label: "Subtext (optional)", name: "subtext", widget: "text", required: false }

  - name: "schedule_collection"
    label: "Schedule"
    files:
      - label: "Alle Termine"
        name: "schedule_list"
        file: "src/data/schedule.json"
        fields:
          - label: "Termin"
            name: "schedule"
            widget: "list"
            summary: "{{time}}"
            fields:
              - { label: "Zeit", name: "time", widget: "string"}
              - { label: "Titel", name: "title", widget: "string"}
              - { label: "Text", name: "description", widget: "text"}
