backend:
  name: github
  repo: pangv/auszweiwirdeins # Ersetze dies durch dein tats√§chliches Repo
  branch: main

media_folder: "public/images/uploads" # Wo Bilder gespeichert werden
public_folder: "/images/uploads"

collections:
  - name: "hotels"
    label: "Hotel Empfehlungen"
    file: "src/data/hotels.json" # Pfad zu deiner JSON-Datei
    fields:
      - label: "Hotels"
        name: "hotels"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Bild", name: "image", widget: "image" }
          - { label: "Adresse", name: "address", widget: "string" }
          - { label: "Preisspanne", name: "price", widget: "string" }
          - { label: "Entfernung", name: "distance", widget: "text" }
          - { label: "Beschreibung", name: "description", widget: "text" }